### ISSUE TITLE
Not redirecting to checkout/cart page after added to the cart

### ISSUE THREAD

**Issue by ravikumarkarri** [varunsridharan/woocommerce-quick-buy#40] opened 2020-08-19 04:15 UTC
**Describe the bug**
I have setup to redirect to redirect to checkout page when we click on the buy now button. But product is added to cart successfully. 

Please check the below link for your reference.
https://hirawats2.owncreek.com/shop/blue-medical-uniform-scrub-half-sleeve/

**To Reproduce**
1. Go to https://hirawats2.owncreek.com/shop/blue-medical-uniform-scrub-half-sleeve/
2. Click on 'Buy Now'
3. See error

**Expected behavior**
Product to need to added to cart then redirect to checkout page.

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser  - All
 - Version - Updated versions

**Comment by varunsridharan** [comment] 2020-08-22 06:08
Duplicate of #39

**Closed as completed** 2020-08-28 03:32 UTC
Labels: bug
